[package]
name = "y24d01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../../aoc" }
radsort = "0.1.1"
rayon = "1.10.0"
