[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-macro = { path = "../aoc-macro" }

binary-heap-plus = "0.5.0"
itertools = "0.12.0"
num-traits = "0.2.17"
