[package]
name = "y22d05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inpt = "0.1.1"
itertools = "0.10.5"
petgraph = "0.6.2"
aoc = { path = "../../aoc" }
regex = "1.7.0"
